---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# BlastOverview

<!-- badges: start -->
<!-- badges: end -->

The goal of BlastOverview is to ...

## Installation

The development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("Tsmnbx/BlastOverview")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(BlastOverview)
## basic example code
```

First you have to Blast the results to Create a Data Frame of a Blast search
```{r }
library(BlastOverview)
#Here is the TakifuguRubripesChromosome12 which as a gene on Chrosome 12 of
# a Takifugu Rubripes a type of puffer fish
db<-Blast(TakifuguRubripesChromosome12)

```

Next you can create a wordcloud from the results
```{r }
library(BlastOverview)
#Here is the TakifuguRubripesChromosome12 which as a gene on Chrosome 12 of
# a Takifugu Rubripes a type of puffer fish
db<-Blast(TakifuguRubripesChromosome12)
WordGraph(db)

```

